// <auto-generated />
using System;
using MUS.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUS.Migrations
{
    [DbContext(typeof(MusDbConText))]
    [Migration("20241017165321_Ad")]
    partial class Ad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUS.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<string>("TenAlbum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.AlbumNhacSi", b =>
                {
                    b.Property<Guid?>("NhacSiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlBumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NhacSiId", "AlBumId");

                    b.HasIndex("AlBumId");

                    b.ToTable("AlbumNhacSis");
                });

            modelBuilder.Entity("MUS.Entities.BaiNhac", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanFileAmNhac")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DuongDanHinhAnh")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LoiBaiHat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("LuotNghe")
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NhacSiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TamTrangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBaiNhac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TheLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThoiLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ChudeId");

                    b.HasIndex("NhacSiId");

                    b.HasIndex("TamTrangId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("BaiNhac", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.ChuDe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ChuDe", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.NhacSi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhacSi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhacSi", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.TamTrang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTamTrang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TamTrang", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTheLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.AlbumNhacSi", b =>
                {
                    b.HasOne("MUS.Entities.Album", "Album")
                        .WithMany("AlbumNhacSis")
                        .HasForeignKey("AlBumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MUS.Entities.NhacSi", "NhacSi")
                        .WithMany("AlbumNhacSis")
                        .HasForeignKey("NhacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("NhacSi");
                });

            modelBuilder.Entity("MUS.Entities.BaiNhac", b =>
                {
                    b.HasOne("MUS.Entities.Album", "Album")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("FK_Album_BaiNhac");

                    b.HasOne("MUS.Entities.ChuDe", "ChuDe")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("ChudeId")
                        .HasConstraintName("FK_ChuDe_BaiNhac");

                    b.HasOne("MUS.Entities.NhacSi", "NhacSi")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("NhacSiId")
                        .HasConstraintName("FK_NhacSi_BaiNhac");

                    b.HasOne("MUS.Entities.TamTrang", "TamTrang")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("TamTrangId")
                        .HasConstraintName("FK_TamTrang_BaiNhac");

                    b.HasOne("MUS.Entities.TheLoai", "TheLoai")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("TheLoaiId")
                        .HasConstraintName("FK_TheLoai_BaiNhac");

                    b.Navigation("Album");

                    b.Navigation("ChuDe");

                    b.Navigation("NhacSi");

                    b.Navigation("TamTrang");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("MUS.Entities.Album", b =>
                {
                    b.Navigation("AlbumNhacSis");

                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.ChuDe", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.NhacSi", b =>
                {
                    b.Navigation("AlbumNhacSis");

                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.TamTrang", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.TheLoai", b =>
                {
                    b.Navigation("BaiNhacs");
                });
#pragma warning restore 612, 618
        }
    }
}
