// <auto-generated />
using System;
using MUS.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUS.Migrations
{
    [DbContext(typeof(MusDbConText))]
    [Migration("20241124050117_AddThuVien")]
    partial class AddThuVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MUS.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<string>("TenAlbum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.AlbumNhacSi", b =>
                {
                    b.Property<Guid?>("NhacSiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlBumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NhacSiId", "AlBumId");

                    b.HasIndex("AlBumId");

                    b.ToTable("AlbumNhacSis");
                });

            modelBuilder.Entity("MUS.Entities.BaiNhac", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanBanner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDanFileAmNhac")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DuongDanHinhAnh")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("KichThuoc")
                        .HasColumnType("decimal");

                    b.Property<string>("LoiBaiHat")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("LuotNghe")
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NhacSiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QuocGiaId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TamTrangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBaiNhac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TheLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThoiLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ChudeId");

                    b.HasIndex("NhacSiId");

                    b.HasIndex("QuocGiaId");

                    b.HasIndex("TamTrangId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("BaiNhac", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.ChuDe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ChuDe", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.DanhSachPhat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayPhatHanh")
                        .HasColumnType("datetime");

                    b.Property<string>("TenDanhSachPhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DanhSachPhat", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.DanhSachPhat_BaiNhac", b =>
                {
                    b.Property<Guid>("DanhSachPhatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaiNhacId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DanhSachPhatId", "BaiNhacId");

                    b.HasIndex("BaiNhacId");

                    b.ToTable("DanhSachPhat_BaiNhac");
                });

            modelBuilder.Entity("MUS.Entities.LichSuNgheNhac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaiNhacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNghe")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TheLoaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BaiNhacId");

                    b.HasIndex("UserId");

                    b.ToTable("LichSuNgheNhacs");
                });

            modelBuilder.Entity("MUS.Entities.NhacSi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNhacSi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhacSi", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.QuocGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenQuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("QuocGia", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.TamTrang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTamTrang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TamTrang", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.TheLoai", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTheLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.ThuVien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("ThuVien", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.ThuVienBaiNhac", b =>
                {
                    b.Property<Guid>("ThuVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaiNhacId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ThuVienId", "BaiNhacId");

                    b.HasIndex("BaiNhacId");

                    b.ToTable("ThuVienBaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MUS.Entities.AlbumNhacSi", b =>
                {
                    b.HasOne("MUS.Entities.Album", "Album")
                        .WithMany("AlbumNhacSis")
                        .HasForeignKey("AlBumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MUS.Entities.NhacSi", "NhacSi")
                        .WithMany("AlbumNhacSis")
                        .HasForeignKey("NhacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("NhacSi");
                });

            modelBuilder.Entity("MUS.Entities.BaiNhac", b =>
                {
                    b.HasOne("MUS.Entities.Album", "Album")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("FK_Album_BaiNhac");

                    b.HasOne("MUS.Entities.ChuDe", "ChuDe")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("ChudeId")
                        .HasConstraintName("FK_ChuDe_BaiNhac");

                    b.HasOne("MUS.Entities.NhacSi", "NhacSi")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("NhacSiId")
                        .HasConstraintName("FK_NhacSi_BaiNhac");

                    b.HasOne("MUS.Entities.QuocGia", "QuocGia")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("QuocGiaId")
                        .HasConstraintName("FK_QuocGia_BaiNhac");

                    b.HasOne("MUS.Entities.TamTrang", "TamTrang")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("TamTrangId")
                        .HasConstraintName("FK_TamTrang_BaiNhac");

                    b.HasOne("MUS.Entities.TheLoai", "TheLoai")
                        .WithMany("BaiNhacs")
                        .HasForeignKey("TheLoaiId")
                        .HasConstraintName("FK_TheLoai_BaiNhac");

                    b.Navigation("Album");

                    b.Navigation("ChuDe");

                    b.Navigation("NhacSi");

                    b.Navigation("QuocGia");

                    b.Navigation("TamTrang");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("MUS.Entities.DanhSachPhat", b =>
                {
                    b.HasOne("MUS.Entities.User", "User")
                        .WithMany("DanhSachPhats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_User_DanhSachPhat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MUS.Entities.DanhSachPhat_BaiNhac", b =>
                {
                    b.HasOne("MUS.Entities.BaiNhac", "BaiNhac")
                        .WithMany("DanhSachPhat_BaiNhacs")
                        .HasForeignKey("BaiNhacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MUS.Entities.DanhSachPhat", "DanhSachPhat")
                        .WithMany("DanhSachPhat_BaiNhacs")
                        .HasForeignKey("DanhSachPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiNhac");

                    b.Navigation("DanhSachPhat");
                });

            modelBuilder.Entity("MUS.Entities.LichSuNgheNhac", b =>
                {
                    b.HasOne("MUS.Entities.BaiNhac", "BaiNhac")
                        .WithMany("LichSuNgheNhacs")
                        .HasForeignKey("BaiNhacId");

                    b.HasOne("MUS.Entities.User", "User")
                        .WithMany("LichSuNgheNhacs")
                        .HasForeignKey("UserId");

                    b.Navigation("BaiNhac");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MUS.Entities.ThuVien", b =>
                {
                    b.HasOne("MUS.Entities.User", "User")
                        .WithOne("ThuVien")
                        .HasForeignKey("MUS.Entities.ThuVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MUS.Entities.ThuVienBaiNhac", b =>
                {
                    b.HasOne("MUS.Entities.BaiNhac", "BaiNhac")
                        .WithMany("ThuVienBaiNhacs")
                        .HasForeignKey("BaiNhacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MUS.Entities.ThuVien", "ThuVien")
                        .WithMany("ThuVienBaiNhacs")
                        .HasForeignKey("ThuVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiNhac");

                    b.Navigation("ThuVien");
                });

            modelBuilder.Entity("MUS.Entities.User", b =>
                {
                    b.HasOne("MUS.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Role_User");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MUS.Entities.Album", b =>
                {
                    b.Navigation("AlbumNhacSis");

                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.BaiNhac", b =>
                {
                    b.Navigation("DanhSachPhat_BaiNhacs");

                    b.Navigation("LichSuNgheNhacs");

                    b.Navigation("ThuVienBaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.ChuDe", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.DanhSachPhat", b =>
                {
                    b.Navigation("DanhSachPhat_BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.NhacSi", b =>
                {
                    b.Navigation("AlbumNhacSis");

                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.QuocGia", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MUS.Entities.TamTrang", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.TheLoai", b =>
                {
                    b.Navigation("BaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.ThuVien", b =>
                {
                    b.Navigation("ThuVienBaiNhacs");
                });

            modelBuilder.Entity("MUS.Entities.User", b =>
                {
                    b.Navigation("DanhSachPhats");

                    b.Navigation("LichSuNgheNhacs");

                    b.Navigation("ThuVien");
                });
#pragma warning restore 612, 618
        }
    }
}
